/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Barbu API
 * OpenAPI spec version: 1
 */
export interface AuthControllerCredentials {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export type Login200 = { [key: string]: unknown };

export type Register200 = { [key: string]: unknown };

export type Health200 = { [key: string]: unknown };

export type Me200 = { [key: string]: unknown };

export type loginResponse200 = {
  data: Login200
  status: 200
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {




  return `/auth/login`
}

export const login = async (authControllerCredentials: AuthControllerCredentials, options?: RequestInit): Promise<loginResponse> => {

  const res = await fetch(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authControllerCredentials)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type registerResponse200 = {
  data: Register200
  status: 200
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {




  return `/auth/register`
}

export const register = async (authControllerCredentials: AuthControllerCredentials, options?: RequestInit): Promise<registerResponse> => {

  const res = await fetch(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authControllerCredentials)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}



export type healthResponse200 = {
  data: Health200
  status: 200
}

export type healthResponseSuccess = (healthResponse200) & {
  headers: Headers;
};
;

export type healthResponse = (healthResponseSuccess)

export const getHealthUrl = () => {




  return `/health`
}

export const health = async ( options?: RequestInit): Promise<healthResponse> => {

  const res = await fetch(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthResponse
}



export type meResponse200 = {
  data: Me200
  status: 200
}

export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
;

export type meResponse = (meResponseSuccess)

export const getMeUrl = () => {




  return `/me`
}

export const me = async ( options?: RequestInit): Promise<meResponse> => {

  const res = await fetch(getMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: meResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as meResponse
}
